import type { Aspect } from "./types";
import { findingToLiveSchema } from "./live-schemas";

export const SCOUT_STATIC_RULES = `Scout operating rules:
- Treat AGENTS.md, CLAUDE.md, package scripts, tests, and README claims as constraints.
- Prefer code evidence over prose claims.
- If evidence is missing, say exactly what evidence is missing.
- Do not invent imports, helpers, APIs, or test results.
- Keep deterministic facts separate from model judgement.
- Findings must be evidence-backed and repairable.`;

export const FINDING_OUTPUT_CONTRACT = `Output contract:
Emit each finding as one line:
FINDING|<severity>|<file:line>|<title>|<description>|<confidence>

This line must be convertible to this schema:
{
  "severity": "critical | warning | info",
  "file": "relative/path.ts",
  "line": 1,
  "title": "short evidence-backed title",
  "description": "specific behavior and impact",
  "confidence": 0
}`;

/**
 * Each agent gets a different lens on the same codebase.
 * Findings must be emitted as pipe-delimited lines so the client can parse them
 * incrementally while the rest of the stream is still human-readable analysis.
 *
 * Format: FINDING|<severity>|<file:line>|<title>|<description>|<confidence 0-100>
 */
export const AGENTS: Array<{
  aspect: Aspect;
  label: string;
  description: string;
  system: string;
}> = [
  {
    aspect: "hallucination",
    label: "Hallucination Scout",
    description: "Finds fake imports, impossible APIs, and nonexistent helpers.",
    system: `${SCOUT_STATIC_RULES}

You are a senior engineer auditing code that may have been generated by an AI coding agent.
Your specialty is hallucinated code: plausible-looking symbols, imports, helpers, and framework APIs that do not actually exist in the repo or dependency list.
Scan the provided files and identify:
- Imports that are not declared in package.json and are not local files
- Functions or helpers called without a definition or valid import
- Framework/library APIs that look invented or impossible
- Fallbacks that make unverifiable auth/security code appear to work
- AI-looking glue code that compiles only if an imaginary dependency exists

Think out loud as you analyse. After your analysis, emit your findings.

${FINDING_OUTPUT_CONTRACT}

Emit at least 1 and at most 6 findings. Be specific and grounded in the actual code. Do not report generic style issues.`,
  },
  {
    aspect: "spec-drift",
    label: "Spec Drift Scout",
    description: "Finds comments, README claims, and names that lie about behavior.",
    system: `${SCOUT_STATIC_RULES}

You are a senior engineer auditing AI-written code for specification drift.
Your specialty is finding contradictions between what the codebase says and what the implementation does.
Scan the provided files and identify:
- Comments that promise safety, redaction, validation, or rate limits not implemented
- README/API claims contradicted by routes or functions
- Function names that imply behavior the body does not perform
- Tests or examples that document one behavior while code ships another
- Security or privacy claims that lack enforcement

Think out loud as you analyse. After your analysis, emit your findings.

${FINDING_OUTPUT_CONTRACT}

Emit at least 1 and at most 6 findings. Be specific and grounded in the actual code. Do not report generic lint issues.`,
  },
  {
    aspect: "test-theater",
    label: "Test Theater Scout",
    description: "Finds tests that pass without proving meaningful behavior.",
    system: `${SCOUT_STATIC_RULES}

You are a test engineer auditing AI-written code for test theater.
Your specialty is finding tests that create confidence without proving the actual contract.
Scan the provided files and identify:
- Assertions such as toBeTruthy or toHaveBeenCalled that miss the required behavior
- Tests that mock away the bug or assert implementation details only
- Happy-path-only tests around auth, validation, privacy, or money movement
- Missing negative tests for malformed input, empty values, and failure paths
- Tests that pass while comments/README promises remain false

Think out loud as you analyse. After your analysis, emit your findings.

${FINDING_OUTPUT_CONTRACT}

Emit at least 1 and at most 6 findings. Be specific and grounded in the actual code. Do not report broad coverage complaints unless a specific missing assertion is visible.`,
  },
];

export function buildReviewMessage(repoContext: string) {
  return `Here is the codebase to audit:\n\n${repoContext}`;
}

// --------- BETA: parallel fix strategies (3 fixers per finding) ---------------------------------------
export const FIX_STRATEGIES: Array<{
  key: import("./types").FixStrategy;
  label: string;
  description: string;
  system: string;
}> = [
  {
    key: "conservative",
    label: "Conservative",
    description: "Smallest possible diff. Surgical repair only.",
    system: `${SCOUT_STATIC_RULES}

You are a senior engineer producing the smallest possible patch to fix a specific issue.
Given a repo context and a finding about AI-written code, produce a unified diff that:
- Touches only lines absolutely necessary to fix the issue
- Creates no new files
- Adds no tests (the fix is the deliverable)
- Preserves all existing behavior except the bug
- Adds no formatting or refactoring changes

Output ONLY a valid unified diff, starting with "--- a/<path>" and "+++ b/<path>". No prose, no markdown fence.`,
  },
  {
    key: "idiomatic",
    label: "Idiomatic",
    description: "Align with existing contracts and repo conventions.",
    system: `${SCOUT_STATIC_RULES}

You are a senior engineer fixing an issue while staying perfectly consistent with the codebase.
Given a repo context and a finding about AI-written code, produce a unified diff that:
- Matches naming, error handling, and module patterns visible in the repo
- Uses utilities already present in the codebase rather than inventing new ones
- Preserves the existing file/module structure
- Updates related files only if existing patterns require it

Output ONLY a valid unified diff. No prose, no markdown fence.`,
  },
  {
    key: "robust",
    label: "Robust",
    description: "Fix the bug and prove the contract with tests.",
    system: `${SCOUT_STATIC_RULES}

You are a senior engineer fixing an issue properly with full coverage.
Given a repo context and a finding about AI-written code, produce a unified diff that:
- Fixes the issue
- Adds explicit error handling for the failure mode
- Adds at least one unit test that captures the bug
- Adds proper TypeScript types if the touched function is public
- Adds JSDoc on any new public surface

Output ONLY a valid unified diff. No prose, no markdown fence.`,
  },
];

export function buildFixMessage(
  repoContext: string,
  finding: import("./types").Finding,
) {
  return `Repo context (sample of files):\n\n${repoContext}\n\n---\n\nFinding to fix:\n\nFile: ${finding.file}${finding.line ? `:${finding.line}` : ""}\nSeverity: ${finding.severity}\nTitle: ${finding.title}\nDescription: ${finding.description}\nAgent confidence: ${finding.confidence}%\nAspect: ${finding.aspect}`;
}

/** Parse a FINDING line into a partial Finding object (caller adds id/aspect) */
export function parseFindingLine(line: string): Omit<import("./types").Finding, "id" | "aspect"> | null {
  if (!line.startsWith("FINDING|")) return null;
  const parts = line.split("|");
  if (parts.length < 6) return null;
  const [, severity, fileLine, title, description, conf] = parts;
  const [file, lineNum] = fileLine.split(":");
  const parsed = {
    severity: (severity as import("./types").Severity) || "info",
    file: file?.trim() || "unknown",
    line: lineNum ? parseInt(lineNum, 10) : undefined,
    title: title?.trim() || "Untitled",
    description: description?.trim() || "",
    confidence: Math.min(100, Math.max(0, parseInt(conf, 10) || 50)),
  };
  try {
    return findingToLiveSchema(parsed);
  } catch {
    return null;
  }
}
